### ISSUE TITLE
Cannot find Command "Bridge To Kubernetes: Configure"

### ISSUE THREAD

**Issue by ckapatch** [microsoft/mindaro#191]
**Describe the bug**
I've been trying to get a new project setup to use Bridge To Kubernetes but cannot seem to find the command. I have existing projects that are setup and working but a new one I can't get to work
 
**To Reproduce**
1. Created Project
2. Ran Project Once to get initial launch configuration
3. Open commands
4. Search for "Bridge to Kubernetes: Configure"

![Screen Shot 2021-06-18 at 12 48 22 PM](https://user-images.githubusercontent.com/855721/122605875-48e8ea00-d035-11eb-929a-73011d6baef6.png)
![Screen Shot 2021-06-18 at 12 48 28 PM](https://user-images.githubusercontent.com/855721/122605881-4be3da80-d035-11eb-8ea6-d83c822dc314.png)
![Screen Shot 2021-06-18 at 12 49 20 PM](https://user-images.githubusercontent.com/855721/122605892-4e463480-d035-11eb-8f83-f806a68b3c8e.png)

 I suppose I'm doing something really obviously wrong. I just can't figure out what it is.

**Comment by daniv-msft** [comment]
Thanks @ckapatch for opening this issue. This is definitely unusual.

Looking at the second screenshot you shared, we can see that the extension initialized properly, which is good to validate.

The first thing I notice that could explain what you see if that in your command search, the input field doesn't start with ">". I see that you're not using Windows, so maybe it doesn't apply for you, but on my VS Code this makes a difference between commands and searching files by name:
* Commands:
![image](https://user-images.githubusercontent.com/48293037/122607264-294ec300-d02f-11eb-8c60-b4082065f576.png)

* Search files by name:
![image](https://user-images.githubusercontent.com/48293037/122607305-37044880-d02f-11eb-8f1c-08297c05232f.png)

Do you see anything similar? Also, do you see other VS Code commands ("Extensions: Install from VSIX..." for example) in the list?

If this is not the root cause of the issue, would it be possible for you to:
* Check that our "Kubernetes" status bar menu item is present and looks good (please click on it as well to open the menu):
![image](https://user-images.githubusercontent.com/48293037/122607805-fe18a380-d02f-11eb-96e1-88b81d334143.png)

* Send us the logs mentioned in your screenshot number 2?

Thanks!

**Comment by ckapatch** [comment]
thanks @daniv-msft for the prompt response.

that was it. You need the '>' in the front of the command. Thanks for the assistance, it was driving me nuts.

Cheers.
