### ISSUE TITLE
Isolation in Visual Studio

### ISSUE THREAD

**Issue by FrankVDL-Trivec** [microsoft/mindaro#20]
I don't see a way to setup isolation in Visual Studio.

In VS Code the extension handles the isolation correctly but this is not working in the "regular" Visual Studio.

**Comment by Gordonby** [comment]
Hi @FrankVDL-Trivec 
You're right, we don't yet have the feature in our Visual Studio Extension. 
It's on the [roadmap](https://github.com/microsoft/mindaro/projects/1#card-42586126), and work is in progress.

**Comment by FrankVDL-Trivec** [comment]
Any idea on an ETA ?

We are using DevSpaces rather heavy but it's causing a lot for problems to keep it up an running.
So we hoop this might be a better solution for us.

**Comment by Gordonby** [comment]
I'll check to share if we have a date we can share.
In the meantime, have you tried the experience in VSCode?  I'm assuming you're using c#?

**Comment by FrankVDL-Trivec** [comment]
Yes we checked in VSCode for our frontend development and there it works good.
For the backend and API services we are using Visual Studio so ....

**Comment by Gordonby** [comment]
@FrankVDL-Trivec - this sounds a little like one of the current bugs thats being fixed.  as a possbible workaround, can i get you to change your isolateAs value?  From "isolateAs": "frank.va-2a44" to "isolateAs": "f"

**Comment by dahovey** [comment]
It seems isolation in Visual Studio 2019 is supported based on the UI, is this correct?

![image](https://user-images.githubusercontent.com/22330242/93247559-55a57e00-f743-11ea-8d69-e1834c8e633c.png)

**Comment by daniv-msft** [comment]
@dahovey Absolutely, thanks! We just released the isolation feature in Visual Studio 1-2 weeks ago.

@FrankVDL-Trivec Could you please give a try to the latest version of the Visual Studio, and let me know if you run into any issues?

**Comment by FrankVDL-Trivec** [comment]
Without isolation it seems to be working find.
With isolation enabled we get "One or more errors occurred"

![image](https://user-images.githubusercontent.com/60176252/93353533-540bb100-f83c-11ea-84a3-2be82c8d3573.png)

Can this be the same problem where the name of the isolation is to long ?
We don't seem to be able to see the setting in the launcSettings.json file, where can we change the "isolateAs" name ?

**Comment by daniv-msft** [comment]
Thank you @FrankVDL-Trivec for trying this, and sorry you encounter this issue.

As mentioned in https://github.com/Azure/dev-spaces/issues/404, I agree the current error message isn't very helpful. :(
We are presently improving the UX in Visual Studio so that errors are better surfaced. We expect that this will be available in Visual Studio early next week.

In the meantime, you can have a look at our logs in `%TEMP%\Local Process with Kubernetes` to see what goes wrong. Specifically, I'd suggest to reproduce the bug and look at the most recents `lpk-library-*` files.
If you want to, you can also forward these logs files to me (`daniv@microsoft.com`) so that I can have a look at them.

Finally, if you want to modify the isolation header (similarly to VS Code), you have to open your project user settings (`*.csproj.user` file). In this file, you will see a field called `RoutingHeader`, that corresponds to the isolation header.

**Comment by simyco** [comment]
i also have probelms with isolation, attached my logs [bridge-mindarocli-2020-09-25-08-44-49-17232.zip](https://github.com/microsoft/mindaro/files/5281636/bridge-mindarocli-2020-09-25-08-44-49-17232.zip)

**Comment by pragyamehta** [comment]
Hi @simyco Thanks for reporting your issue! It would be great if you could attach the logs from the routing manager running in your namespace. You can retrieve the logs by running the below commands : 
1. Retrieve the routing manager pod name
       kubectl -n {namespace} get pods
2. Retrieve logs for the routing manager pod
      kubectl -n {namespace} logs {routing manager pod name from step 1}  > routing-manager-logs.txt

Kindly send the routing-manager-logs.txt to us and we will investigate and get back to you!

**Comment by nsinitsin** [comment]
Hi @pragyamehta and @daniv-msft.
I think this is a best place to ask about error related with isolation mode is here.
I work with VS 2019. Without selected option "Isolate your local" it means by default all requests go through my local machine all works fine.

But when I choose option with isloation, I have an error in VS 
![image](https://user-images.githubusercontent.com/12630094/94585781-6217f380-0278-11eb-8bb6-c62a55449acb.png)

What i'm doing wrong? Also at @dahovey message he has launch browser to: with URL in my case that list is empty. 

in AKS I have several ingress objects.  If you need I can send logs from route manager pod. Just send me an email, because I don't wnat to share logs (where I see sensetive information) here.

Thanks in advance.

**Comment by pragyamehta** [comment]
Hi @nsinitsin Thanks for reaching out! Yes, routing manager pod logs would be extremely helpful. Can you please send those over to my email pragme@microsoft.com and I will take a look. 
You can retrieve the logs by running the below commands :

1. Retrieve the routing manager pod name
kubectl -n {namespace} get pods
2. Retrieve logs for the routing manager pod
kubectl -n {namespace} logs {routing manager pod name from step 1} > routing-manager-logs.txt

Kindly send the routing-manager-logs.txt to us and we will investigate and get back to you!
