### ISSUE TITLE
Dead link in Visual Studio wizard

### ISSUE THREAD

**Issue by Vaccano** [microsoft/mindaro#215]
**Describe the bug**
In Visual Studio, it has a link that says "Learn about routing isolation".  That link takes me to this page:

https://docs.microsoft.com/en-us/visualstudio/bridge/overview-bridge-to-kubernetes?view=vs-2019#using-routing-capabilities-for-developing-in-isolation

That page gives me a 404 error.
 
**To Reproduce**
1. Download Visual Studio 2019 version 16.9.2
2. Setup Bridge To Kubernetes and in the screen where you select your namespace and service, click on the link for "Learn about routing isolation"

 
**Expected behavior**
The link would tell me what header I need to make sure is propagated (instead of a 404).
 
**Logs**
Not Applicable
 
**Environment Details**
Client used (VS Code/Visual Studio): Visual Studio
Client's version: 16.9.2
Operating System: Windows 10
 
**Additional context**
None

**Comment by daniv-msft** [comment]
Thank you very much @Vaccano for creating this issue! We've been working on refactoring our doc recently, and there has been an update issue. The documentation fix has been pushed and should be available very soon.

For your question, the HTTP header you need to propagate between your microservices is "kubernetes-route-as". We will populate it if you use Bridge isolated, and you need to propagate it in your system after that (so that if you debug a specific microservice deep in your architecture, we know whether we should redirect the traffic we receive there to your dev machine or not).
Please see the VS Code doc that is still live for more info: https://code.visualstudio.com/docs/containers/bridge-to-kubernetes#_header-propagation
