### ISSUE TITLE
Any way to gauge progress?

### ISSUE THREAD

**Issue by Vaccano** [microsoft/mindaro#251]
I am normally able to gauge progress of a project based on check-in frequency.  But this project is basically just sample code (not the real code).  So I can't really tell if development is currently underway.  

It is a software development constant that projects sometimes lose favor with those that work on them.

**Is there any way to gauge how interested Microsoft is in continuing to devote resources to Bridge to Kuberentes?**

**Comment by BigMorty** [comment]
Hello @Vaccano! As you rightly noticed, this repo is primarily samples since the Bridge to Kubernetes tooling is not open source. That said, we are currently designing a comprehensive experience for microservice development. As part this, we are determining how Bridge to Kubernetes fits into the new experience.
