### ISSUE TITLE
Launch Bridge to Kubernetes is not added to existing projects

### ISSUE THREAD

**Issue by trhumphries** [microsoft/mindaro#33]
**Describe the bug**
I installed the Bridge to Kubernetes GA version and opened an existing project the launch.json did not get updated to support the add-in. I tried to manually add it using the template support however there is no template for it
 
**To Reproduce**
Open a project that it hasn't been used on

**Expected behavior**
I'd expect it to add a new configuration to the launch.json
 
**Logs**
 
**Environment Details**
Client used 
VS Code:

**Comment by daniv-msft** [comment]
Thank you @trhumphries for reporting this issue.
There are some cases where the Bridge to Kubernetes launch configuration won't be added automatically. For example, it won't be added if there isn't any other launch configuration in the launch.json.
This is because Bridge requires another launch configuration to run locally your project once the connection with your cluster is done.

In order to make sure that Bridge to Kubernetes configures your project, you can run this command in VS Code: `Bridge to Kubernetes: Configure`. If some of the prerequisites are missing, this command will also list them.

**Comment by trhumphries** [comment]
Thanks. I'll try it out and let you know how it goes.

**Comment by daniv-msft** [comment]
Great, thanks @trhumphries!

**Comment by trhumphries** [comment]
When prompted to pick the launch configuration to use to run your configuration locally I choose the .NET Core Launch (web).
Is that the correct one?
When I then use the generated .NET Core launch (web) with Kubernetes it eventually displays an error The prelaunchtask ' bridge-to-kubernetes.compind' terminated with an exit code 1.

**Comment by daniv-msft** [comment]
Yes, the `.NET Core Launch (web)` profile sounds good!

Do you get any error when you look at your VS Code terminal?
You should first see our task connecting to your cluster:
![image](https://user-images.githubusercontent.com/48293037/94036333-0bdb1a00-fd79-11ea-89dc-688f78d8ed19.png)

Then, still in the terminal, you should see the .NET launch configuration being started:
![image](https://user-images.githubusercontent.com/48293037/94036414-22817100-fd79-11ea-9f47-ad5fe449f14b.png)

If the .NET launch configuration starts properly, you should see something like this in the debug console:
![image](https://user-images.githubusercontent.com/48293037/94036593-5066b580-fd79-11ea-9ae2-acea7a861cd8.png)

Do you see any errors at this point? The issue can be related to Bridge not connecting successfully, or to the .NET project not building properly.

**Comment by trhumphries** [comment]
Yep there was a build error I wasn't seeing. Thanks I think I have it working now.

**Comment by daniv-msft** [comment]
Great, glad it works now!
