### ISSUE TITLE
visual studio dialog finds no subscriptions when using an AzureUSGovernment account to find aks clusters.

### ISSUE THREAD

**Issue by catsgotmytongue** [microsoft/mindaro#70]
When using bridge to kubernetes connection dialog in visual studio no subscriptions show in the dropdown when trying to use an AzureUSGovernment account.

The problem seems to be caused by the wrong API being used to communicate with azure to get subscriptions.
Inspecting this problem with fiddler showed me it was using a get request to https://management.azure.com/subscriptions?api-version=2016-06-01 to get subscriptions for the dialog. 

I believe for the azure us government account I'm using it should be using https://management.usgovcloudapi.net/subscriptions?api-version=2016-06-01 as I see the subscription I need in the response when I use postman to make the request. There doesn't seem to be anyway to change this and makes me think that bridge to kubernetes is not taking other azure clouds besides AzureCloud.

**To Reproduce**
1. using an azure us government account attempt to connect to bridge to kubernetes in visual studio (my version is 16.7.7 latest at writing).
2. add the account from the dialog (note adding the account with the correct government cloud in options>accounts doesn't populate the account in the user dropdown of the bridge dialog)
3. Selecting the government user in the dropdown yields no subscriptions, looking at the request behind the dialog is using the wrong endpoint address as I mentioned above.

 
**Expected behavior**
When selecting a valid government user in a government cloud it should find the subscriptions the user has access to using the correct api.
 
**Logs**
no logs relevant to this that I saw at those paths and nothing produced an error it simply didn't work.
 
**Environment Details**
Visual studio 2019 v16.7.7

**Comment by daniv-msft** [comment]
Thank you @catsgotmytongue for reporting this issue.
Adding @danegsta to the issue, as he knows more about the authentication API we use in Visual Studio.

In order to unblock you in the meantime, if you have a local kubeconfig for this cluster and can communicate with it through kubectl, please consider using the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=mindaro.mindaro) that relies only on the kubeconfig for authentication.

**Comment by danegsta** [comment]
Thanks for reporting this @catsgotmytongue; we're working on verifying a fix that would go out with the next release of the VS extension (currently targeting early next week).

**Comment by catsgotmytongue** [comment]
Thanks for the quick response. 

I was scratching my head at why it wasn't working until I took the time to look at fiddler logs and realized it was using the wrong api.

**Comment by catsgotmytongue** [comment]
Any word on this ? I'm guessing that the release was pushed out further ?

**Comment by danegsta** [comment]
We ended up finding a bug during our test passes that needed to be fixed before we released; we've got a release candidate now that we're planning on pushing to the marketplace this coming Monday (11/9).

**Comment by catsgotmytongue** [comment]
cool. Thanks for your work and quick responses !

**Comment by danegsta** [comment]
Build 1.3.20201106.1 was just pushed to the marketplace with support for sovereign cloud accounts.

**Comment by catsgotmytongue** [comment]
Thank you,

I'll give this a try as soon as I can.

**Comment by catsgotmytongue** [comment]
so I tried out this updated version with my AKS cluster and now I think I'm seeing a different issue because it thinks my cluster is not an aks cluster:
![image](https://user-images.githubusercontent.com/506072/98596989-26b41000-228d-11eb-8fba-93ce219f882c.png)

**Comment by danegsta** [comment]
It looks like there's a check that was added for earlier VS Code preview releases of Bridge to Kubernetes that is triggering in VS as well. Fortunately, the check is controlled by an environment variable, so you should be able to disable it by adding ALLOW_NON_AZURE_CLUSTERS=true to your environment variables and restarting Visual Studio. It won't actually add support for non-Azure clusters in the VS extension, but it should prevent the tooling from only recognizing AKS clusters in the Azure Public cloud.

**Comment by catsgotmytongue** [comment]
well I get a different error but I believe that it's because the cluster doesn't have the deployment/pods to actually handle things.

Is there a quick command line to re-start the kubernetes bridge or re-add the components ?

this is what I get now after adding the env var:
![image](https://user-images.githubusercontent.com/506072/98604911-6680f480-2299-11eb-867e-a97899779190.png)

**Comment by daniv-msft** [comment]
@catsgotmytongue If you start Bridge from Visual Studio, we should validate that the components we expect are present cluster-side and recreate them as needed. However, as you suggest, it is possible that we might encounter an issue when doing so.

Could you please let us know if you can see the pods we create in your cluster once you start Bridge to Kubernetes: `routingmanager-*` if you use isolation, and `*-restore-*` in all cases?
![image](https://user-images.githubusercontent.com/48293037/98760061-534c5280-2387-11eb-8200-245818087cf0.png)

Also, given the error you're seeing, it is more likely that the logs would help us. Would it be possible for you to provide them to us?
If you don't want to attach them publicly on GitHub, you can also send them to us by email: `BridgeToKubernetes@microsoft.com`

* Bridge to Kubernetes logs: %TEMP%/Bridge to Kubernetes
* Visual Studio logs: %temp%\Microsoft.VisualStudio.Kubernetes.Debugging

**Comment by catsgotmytongue** [comment]
Sorry, I was out a few days so didn't respond earlier.

Those were missing when I checked after seeing the error but I've since had to re-create the cluster I was using anyway and I'll have to when my networking configuration is stable and working (another team is working on that) again.

when I re-create the cluster I'll have to try again, until then I don't have a cluster worth testing it on. My agency requires a specific network configuration they're trying to work in so I'll have to wait until they figure that part out.

**Comment by daniv-msft** [comment]
All right, thanks @catsgotmytongue for the heads up!

**Comment by catsgotmytongue** [comment]
So today I was able to finally try again.

I was able to get the subscription to show up in the dialog and select the service I want to debug.

I'm now getting a different problem preventing me from the attaching debugger to the pod in visual studio, at the moment I'm trying to make sure it isn't something on our end.

This particular issue I started seems to be fixed though

**Comment by daniv-msft** [comment]
Thanks @catsgotmytongue for the update. Please let us know if we can help once you clarified things on your end.

**Comment by catsgotmytongue** [comment]
I'm a little puzzled now if our firewall is getting in the way again, its quite likely.

I am reading the logs bridge created to get an idea for how all the things are happening.

Is there something that explains what's happening? 
I can see a "restore" Job getting created and I can see endpointmanager comes up but sometimes gets killed because of some kind of idle check.
I can see that bridge is finding my pod and attempting to something with web sockets and port-forwarding but that's as far as it seems to get.

I'm not sure but the firewall might be preventing this from finishing its communication

what are the send/receive loops and Port Listener ?

I assume my dev machine is where the port listener lives and port 50362 is a tcp port on it ?
what's the connection between port 50362 and 50051, is 50051 a port on the pod or the container what does it represent ?

2020-12-07T22:17:23.0786478Z | Library | TRACE | PortListener created on 50362
2020-12-07T22:17:23.0791794Z | Library | TRACE | PortListener started on 50362
2020-12-07T22:17:23.0794184Z | Library | TRACE | Starting listening 50362 : 50051
2020-12-07T22:17:23.1425083Z | Library | TRACE | Accept 50362 to 50051
2020-12-07T22:17:23.1458623Z | Library | TRACE | Port forward pod-588bc8cd54-ttp6z 50362:50051 50364 : Run send loop
2020-12-07T22:17:23.1525041Z | Library | TRACE | Creating web socket for pod-588bc8cd54-ttp6z 50051
2020-12-07T22:17:24.0400350Z | Library | TRACE | Dependency: Kubernetes <json>{"target":"WebSocketPodPortForwardAsync","success":true,"duration":null,"properties":{}}</json>
2020-12-07T22:17:24.0410385Z | Library | TRACE | Web socket for pod-588bc8cd54-ttp6z 50051 created.
2020-12-07T22:17:24.0446690Z | Library | TRACE | Port forward pod-588bc8cd54-ttp6z 50362:50051 50364 : Run receive loop

it does this several times, switching the port used in the send/receive loops:
2020-12-07T22:18:17.9202360Z | Library | TRACE | Accept 50362 to 50051
2020-12-07T22:18:17.9207522Z | Library | TRACE | Port forward pod-588bc8cd54-ttp6z 50362:50051 50451 : Run send loop
2020-12-07T22:18:17.9209633Z | Library | TRACE | Creating web socket for pod-588bc8cd54-ttp6z 50051
2020-12-07T22:18:18.7916676Z | Library | TRACE | Dependency: Kubernetes <json>{"target":"WebSocketPodPortForwardAsync","success":true,"duration":null,"properties":{}}</json>
2020-12-07T22:18:18.9452122Z | Library | TRACE | Web socket for pod-588bc8cd54-ttp6z 50051 created.
2020-12-07T22:18:18.9454694Z | Library | TRACE | Port forward pod-588bc8cd54-ttp6z 50362:50051 50451 : Run receive loop
2020-12-07T22:18:18.9455196Z | Library | TRACE | Port forward pod-588bc8cd54-ttp6z 50362:50051 50451 : RemoteConnection closed.

Visual studio just spins while filling this log

**Comment by catsgotmytongue** [comment]
also I am never seeing a routing manager pod, as described in one of the previous comments. 

What could prevent the pod from instantiating ?

**Comment by daniv-msft** [comment]
The main idea behind Bridge to Kubernetes is quite simple, but there are multiple subtle cases that can make it more complex.

If you didn't already, I'd suggest to take a look at this page that explains what happens when we start the connection, especially the part after `When Bridge to Kubernetes establishes a connection to your cluster, it:`: https://docs.microsoft.com/visualstudio/containers/overview-bridge-to-kubernetes#using-bridge-to-kubernetes

Also, a couple of comments:
* Is it possible that your cluster has specific RBAC restrictions? If yes, please have a look at this page: https://docs.microsoft.com/visualstudio/containers/overview-bridge-to-kubernetes#rbac-authorization
* Are you able to run the `kubectl port-forward` command for this cluster? If we have the RBAC authorizations mentioned above, being able to run this command is pretty much everything we need, as all communications go through this. This port-forwarding/web socket logs are what you see in the logs when we initiate the communication with our remote agent in the cluster (cf. the documentation above).
* Because all communications go through port forwarding (specifically through SignalR over port forwarding), we don't need a public ingress or any public endpoint on the cluster.
* The "restore" job you mention is created as a security so that even if our Visual Studio/VS Code client crashes, we'll still automatically restore the target service to its original state when debug stops. If everything goes well and the clients do their job, this "restore" job will never be used.
* The EndpointManager is one of the processes we run locally to replicate on your local machine your cluster's environment. Because we need to have administrator permissions to update the etc/hosts file or stop Windows services running locally and blocking ports, the EndpointManager needs to run with elevated privileges.
Because asking for administrator permissions every time we debug would be painful, the EndpointManager stays alive for the whole time of the debug session + 15 minutes. If users start another debugging session in this window, they won't need to provide administrator permissions again. After 15 minutes, the EndpointManager automatically stops, which is what you saw in the logs.
* If you set up Bridge to use isolation in the configuration modal in Visual Studio, I'd suggest to disable it for now: adding isolation requires another component running in your cluster (the routing manager), so simplifying the number of components involved will help understanding what goes wrong.

**Comment by catsgotmytongue** [comment]
That was very helpful. I have debugging working now.

In my case checking isolation mode made it connect a debugger, having it unchecked didn't work at all (just spins and eventually crashes).

**can you clarify this point please ?
"Because all communications go through port forwarding (specifically through SignalR over port forwarding), we don't need a public ingress or any public endpoint on the cluster"**

I see the localhost and port and how that is port-forwarded to the cluster

**Where can I look to find or construct the full url for the service that is debugging (documentation example was http://john.dev.app.52.18.10.14.nip.io), that will add the initial routing header without an ingress route on my development machine?** 

also this route because of the way the app interacts with Word must be https, is that even possible with bridge or must I use a public ip and ingress at that point, I'm pretty sure https is not possible with bridge? 

I was using dev spaces with an ingress previously on azure commercial but my agency required us to move to azure government so I'm having to change things a little.

$GENERATED_NAME is like "$myusername-$suffix" 
$SERVICE_NAME is documents
$THE_REST ?

"$GENERATED_NAME.$SERVICE_NAME.$THE_REST" ?

I have a service that normally would be the entry point to the application via an ingress route:
$INGRESS_URL/documents for example

**Comment by catsgotmytongue** [comment]
@daniv-msft 

Ok. for the record I think I have finally worked out the issues holding me back, some of them internal.

This is fixed for me, I recommend closing the issue now

**Comment by daniv-msft** [comment]
@catsgotmytongue Thank you for your reply, and apologies I didn't reply earlier.
Glad you are now unblocked! Please don't hesitate to reach out to us again if we can help you in the future.
